swagger: '2.0'
info:
  description: 'Документация OpenAPI 2.0 (Swagger) для тестового задания в Xsolla School 2021 Backend.'
  version: 0.2.1
  title: Xsolla School 2021. Backend
  contact:
    email: kolya-perminov@ya.ru
schemes:
  - https
  - http
paths:
  /goods/element:
    post:
      description:
      responses:
        '200':
          description: OK
    put:
      description:
      responses:
        '200':
          description: OK
    get:
      description:
      responses:
        '200':
          description: OK
    delete:
      description:
      responses:
        '200':
          description: OK
  /goods/batch:
    post:
      description:
      responses:
        '200':
          description: OK
    put:
      description:
      responses:
        '200':
          description: OK
    get:
      description:
      responses:
        '200':
          description: OK
    delete:
      description:
      responses:
        '200':
          description: OK
